---
title: "India against COVID19"
author: "Rahul Nayak"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(
    input_file,
    encoding=encoding,
    output_file=file.path(
      dirname(input_file), 
      out_dir, 
      'index.html'
      )
    )
  })
---

### Data Sources
Crowd Sourced Data
https://www.covid19india.org/

Ministry of Health and Family Welfare Data hosted on this repository
https://github.com/rahulnyk/covid19_india_data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup libraries, include=FALSE}
  library(tidyverse)
  library(lubridate)
  library(viridis)
  library(readr)
  library(janitor)
  library(kableExtra)
  # library(plotly)
  source('./source_crowd_data.r')
  source('./source_official_data.r')
```

```{r calculate data, include = FALSE}
  source('./source_crowd_data.r')
  source('./source_official_data.r')
  dc <- build_crowd_data()
  do <- build_official_data()
  d <- rbind(do, dc)
  
  ## Statewise Data
  
  data_panindia <- dc %>% group_by(Date) %>% summarize(Total = sum(Total)) %>%
  mutate(StateUt = "India Total") %>% ungroup()

  data_states <- dc %>% select(StateUt, Date, Total) %>% ungroup()
  
  data_statewise <- rbind(data_panindia, data_states) %>%
    mutate(Day = as.integer(strftime(Date, format = "%j")) ) %>%
    ###
    group_by(StateUt) %>% 
    mutate( DaysSince0 = Day - min(Day)  ) %>% 
    mutate( MaxDays = max(DaysSince0) ) %>%
    ungroup() %>%
    ###
    filter(Total > 2) %>%
    mutate(label =  paste(Total, StateUt, sep=" | "))
  
```

## India Current Status {.tabset}

### Total number of cases pan India 

```{r include = FALSE}
  
  data_total <- d %>% 
    pivot_longer(-c(StateUt, Date, Source), values_to = "Cumulative", names_to = "Status") %>%
    group_by(Date, Source, Status) %>% 
    summarise(Cumulative = sum(Cumulative)) %>% 
    filter( Date > dmy('03-03-2020')) %>%
    ungroup() 
    
  data_abs <- data_total %>% filter(Status != 'Total')
  
  data_label <- data_total %>% filter(Status == 'Total') %>% 
    filter( Date > Sys.Date()-5 )
```


```{r echo=FALSE, fig.cap="Total number of COVID19 cases in India by Date", message=FALSE, warning=FALSE}
  ggplot(data = data_abs,  aes(x = Date, y = Cumulative, fill=Status)) + theme_minimal() +
    geom_bar(stat = 'identity') + facet_wrap(~Source, ncol = 1) + 
    geom_text(
      data = data_label, 
      aes(label = Cumulative), show.legend = F,
      angle = 90, color='white', vjust = 0.5, hjust = 1, nudge_y = -100) + 
    theme(legend.position = "top") +
    scale_fill_viridis_d(begin = 0.1, end = 1) + scale_color_viridis_d(begin = 0.1, end=1)

```


```{r echo=F, results='asis', layout="l-body-outset"}
  data_today <- data_abs %>% 
    filter(Date == Sys.Date()) %>% 
    pivot_wider(values_from = Cumulative, names_from = Source) %>%
    select(-c(Date))
  kable(data_today)
```

### India Daily growth rate 

```{r echo=FALSE, fig.cap="Daily Growth rate of COVID19 cases in India", message=FALSE, warning=FALSE}
  data <- d  %>% select(StateUt, Date, Total, Source) %>% 
    group_by(Date, Source) %>%
    summarise(Total = sum(Total)) %>% group_by(Source) %>%
    mutate( TotalPrev = lag(Total, default = 0, order_by = Date)) %>%
    mutate(  DatePrev = lag(Date, order_by = Date) ) %>% 
    mutate(DateCurPrev = as.integer(Date - DatePrev) ) %>%
    filter( Date > ymd('2020-03-04')	) %>%
    mutate( DailyRate = round((Total - TotalPrev)*100/(DateCurPrev*TotalPrev) ) ) %>%
    ungroup()

  ggplot(
    data = data,  
    aes(x = Date, y = DailyRate, group = Source, color = Source, fill=Source)
    ) + 
  theme_minimal() +
  geom_point(alpha = 0.3, size = 2) + geom_line(linetype = 1, alpha = 0.2) + 
  geom_smooth(alpha = 0.2, size=0.6) +
  labs(y = "Growth rate in Percentage")  + 
  ylim(c(-10, 50)) +
  theme(legend.position = "top") +
  scale_fill_viridis_d(end = 0.6) + scale_color_viridis_d(end=0.6)

```

### Statewise Split

```{r include = FALSE}

  # Calculating Data
  y_max <- max(data_statewise$Total)
  x_max <- max(data_statewise$DaysSince0)
  x_label <- x_max + 5
  yesterday <- Sys.Date()
  
  labels <- data_statewise %>% 
    filter(Date == yesterday) %>% 
    arrange( Total ) %>% 
    # mutate(yend = (y_max/n())*row_number()) %>%
    mutate( yend = ( 2^(  (log2(y_max)/(n()) )*row_number()  )) ) %>%
    select(StateUt, yend)
  
  data_statewise <- left_join(data_statewise, labels, by = c("StateUt") )
  
  data_statewise_latest <- data_statewise %>% filter(Date == yesterday)
```

```{r echo=FALSE, fig.cap="Statewise Split", message=FALSE, warning=FALSE}
  ggplot( data = data_statewise_latest, 
          aes(x=DaysSince0, y=Total, fill = StateUt, size = Total^(0.3) )
          ) +
  geom_point(shape = 21, color = 'lightgrey') + 
  geom_line(size = 0.5, alpha=0.6)  +
  geom_label(
    aes(x=x_label, y = yend, label = label, fill=StateUt),
    color='white', fontface = "bold",
    hjust = 0, size=3) + 
  geom_segment(
    aes(xend = x_label, yend = yend, color = StateUt), 
    linetype = "11", size=0.4, alpha=0.5) +
  theme_minimal() +
  theme(
    axis.text=element_text(size=10, color = "darkgrey"),
    axis.title=element_text(size=12)
  ) +
  theme( legend.position = 'off' ) +
  theme(plot.title = element_text(size = 12, hjust = 0.5) ) +
  theme(plot.margin = margin(15, 160, 15, 10)) +
  coord_cartesian(clip = 'off')  +
  scale_color_viridis_d(option="inferno", end = 0.9) + 
  scale_fill_viridis_d(option="inferno", end = 0.9) + 
  xlab("Number of day since first report") + 
  ylab("Number of cases (Cumulative)")  + 
  scale_y_continuous(trans = 'log2') + scale_radius(
    range = c(1, 15),
    trans = "identity",
    guide = "legend"
  )

```
